### ISSUE TITLE
Missing or incompatible modules in PlasticSourceControl plugin

### ISSUE THREAD

**Issue by visualcodex** [SRombauts/UE4PlasticPlugin#36]
When using the UE4Plastic plugin 1.0.4 for the 4.16.3 build I get missing or incompatible modules in PlasticSourceControl plugin -would you like to disable it? You will no longer be able to open any assets created using it. 
It doesn't matter if I choose yes or no. Both results in the Unreal project exiting and not starting up.

The 1.0.4 does work when I run it on 4.17.1 new unreal project.

And on the 4.16.3 project when I revert back to the UE4PlasticPlugin 1.0.2 (think its 2 could be 3) it opens back as normal and works. When I replace the plugin with the 1.0.4 I get the error message.

Any help more than appreciated.
let me know if you need more info
Kind regards,
First message:
![image](https://user-images.githubusercontent.com/18391857/30514820-52f0a100-9b14-11e7-9a8f-b05e32f71196.png)

When choosing no it does give me another popup before exiting:
![image](https://user-images.githubusercontent.com/18391857/30514801-2b1e6162-9b14-11e7-82bb-fd4ba5c4cf56.png)

Message when exiting:
![image](https://user-images.githubusercontent.com/18391857/30514815-43d56ac0-9b14-11e7-8579-65028ab777b3.png)

**Comment by SRombauts** [comment]
Hi @visualcodex, this is entirely normal, since:
- [1.0.3 release is for UE 4.16](https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.0.3)
- [1.0.4 release is for UE 4.17](https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.0.4)

The fact is those two version are nearly the same, but one is compiled for UE4.16, and the seconde one was rebuilt for UE4.17.
Each version of a UE4 plugin can only work for one version of Unreal Engine.

Cheers!

**Comment by visualcodex** [comment]
Thank you for the quick reply. I got confused by a particular line in the ReadME.md
"UE4PlasticPlugin is a simple [Plastic SCM](https://www.plasticscm.com/) Source Control Plugin for Unreal Engine 4 (UE 4.11 to 4.16)"

Wrongly I assumed that meant that the latest plugin is backwards compatible. 

Thanks for the clarification.

**Comment by SRombauts** [comment]
No problem, I'll see if I can reword it more clearly.
