### ISSUE TITLE
Extremely slow upon BP compile when used with Gluon/cloud

### ISSUE THREAD

**Issue by M-Pixel** [SRombauts/UE4PlasticPlugin#40]
On our artists' computers, where they are using Gluon for partial workspaces that are connected directly to the `cloud` server, the following operations cause a 10 to 20 second "Updating file(s) source control status..." dialog that completely blocks all other operations in the editor.

- Save any asset
- Compile a blueprint
- Restore open assets from the previous session

This happens for assets *that have already been checked-out*. If I'm modifying a uasset that was already checked out, SCM shouldn't be invoked at all.

On our developers' computers, where we have full workspaces connected to replicated repositories, we never experience this issue.

**Comment by SRombauts** [comment]
Thanks for reporting @M-Pixel.
I didn't have time to check this by myself yet, but I will.

The problem is interesting; I think that the plugin obey the Unreal Editor commands, so if you see a long "Updating file(s) source control status" it means that the Editor decided that we have to refresh the status (there is a flag telling the plugin to not rely on cache, but to "force" a refresh).

So:
1. I will have to check if I did code it properly
2. I will see if there are other opportunity for improvements: not checking the lock status on server if the file is already checked-out is a very good suggestion!
3. There could be some more optimization opportunities like #26 and 28: I didn't want to spend to much time for early optims while I didn't have any performances problems by myself.

Could you please send me (privately if you prefer) some logs (form Save\Logs\ sub-folder) of a short user session showcasing your problem? With a short description of the scenario.

The log file should give precise measurement of every commands, and also give the full list of commands, so it should become obvious if to many of them are the cause of the problem, or if any of them are too long due to network/cloud issues.

Regards!

**Comment by M-Pixel** [comment]
Thanks for the response. It looks to me like #26 and #28 probably cover a majority of the slow-downs that I described above. I'll send you logs via email.

**Comment by SRombauts** [comment]
Hi @M-Pixel, I am still interested by logs you could provide, since I will be able to resume work on the plugin.

**Comment by SRombauts** [comment]
Hi @M-Pixel, I've fixed the #26 "Optimization: don't run fileinfo commands on Private or Ignored files" and I've tested successfully with local server and Plastic Cloud.

**Comment by SRombauts** [comment]
I believe I've done all I can think of to improve performances. I will release a new version of the plugin quite soon, and will love to hear about your use case.
Regards!

**Comment by SRombauts** [comment]
Hi @M-Pixel, I've released the 1.1.0 version, hope this will help, please let me know when you can try it!
