### ISSUE TITLE
Diff and history operations take over 20 seconds

### ISSUE THREAD

**Issue by Dzarg** [SRombauts/UE4PlasticPlugin#68]
Hi, at the moment checking the diff in Unreal editor takes over 20 seconds for almost any file in our project. The reasons for this are:
1) We recently did a change to our Game folder's xlink, which caused a checkin of all the files inside it (as far as I know).
2) PlasticSourceControlUtils.cpp's function ParseHistoryResults is called when doing a diff and it will check the whole history, even though it only needs the latest changeset.
3) Changeset 2 in the history has the checkin of all the files and this whole info is read in 4 kB chunks. Total of this info in XML is a bit over 17 MB.

There are some additional reasons why it's as slow as it is (unnecessary string finds, sleeps, reallocations, etc) and it might be possible to make it fast enough by just optimizing everything.
However diffs shouldn't ever need to get the whole history. This is definitely something that should be fixed.

Then some of us also do use the history function of the plugin and that does need to parse the whole history. But it only needs information about the file I'm checking the history on. I don't need information about what other files were changed in the same changeset.

I tested a hack to ignore the changeset 2 when parsing the history and that made diff and history both come up ~instantly instead of the 20+ seconds.

Here's superluminal profile capture of the operation. Let me know if you need more data or if you want me to test something.

![image (1)](https://user-images.githubusercontent.com/94673/68696380-8fd34b80-0585-11ea-8840-4a12fbfa7694.png)

**Comment by SRombauts** [comment]
Hi,

Thanks for this detailed report, I shall have a first look at it ASAP.

Ideally I should try to reproduce the issue and profile it: I would need access to a real game project with a long history in Plastic SCM. But your report is already a good start!

Also, I suspect that a lot of the issue is coming from Unreal Engine behavior itself: it is the Editor that call for the history of a file in order to do the diff, not my plugin.
I also think that some things you see are from default Unreal methods to read the output of a process, etc.

I am pretty sure, though, that a lot can be more optimized in my code, and that I can rewrite my own methods to optimize those of the Engine ( and Pull Requests these change upstream later)

Cheers!

**Comment by SRombauts** [comment]
So I have been digging quite a bit to see if there was something completely off.

When the Editor wants to "Diff Against Depot" it asks for the history of the file.
The plugin does only check for the history of the file, using the `cm history` command, which is quite optimized.
After that, each changeset is queried to get some more details of the change on the file, using the `cm log` command: **this is the part that would need some optimization**. I'll have to review this later to check if what I did can be redone differently (using a different Plastic SCM command etc.).

Regarding all the micro-optimization you propose:

- Sleep() calls are only there to wait for the cm process to output more information: reading from Pipe is more efficient in bigger chunks then looping as fast as possible. This is how it is done in Unreal if I recall correctly.
- The Find() is there to detect the boundaries between commands outputs since we deal here with
a `cm shell` long-running process that we interact with. 
- We could simplify a lot this part, to remove at least some of the copy/append, as well as debug logs. It would optimize a bit, but not on an order of magnitude

=>actually, I bet that the "cm log" command itself is taking a long time to output this 17MB `cm log` on this big changeset. **Perhaps could you test this from the command line**?

About the 4k reads, where do you see this? Is this with the XML Parser?

**Comment by Dzarg** [comment]
Thanks for the quick reply!

Doing a console command `cm log cs:2 > cmlog` takes about 1 second and the size of the file is a bit over 2 MB. `cm log cs:2 --xml > cmlog` on the other hand took 48 seconds and the size is over 17 MB.

Not sure why, but `FString Output = FPlatformProcess::ReadPipe(ShellOutputPipeRead);` the size of the Output seems to be a bit over 4k at maximum for me. That's why I mentioned 4k reads.

Perhaps the data could be requested in other format besides XML to reduce the data size and time spent? For example using the --csFormat and not including {items} as they're 99,99% of the content and shouldn't be needed anyway?

**Comment by SRombauts** [comment]
Hello, I have been able to reproduce the problem by importing into Plastic SCM a game project of 10966 files (18.58GB)
In this case, on a laptop, I get ~20s for a 7MB XML log file.

**Comment by Dzarg** [comment]
Thanks for the update!

Sounds like the same problem and I assume you now have everything you need, but let me know if there's something I can still do to help.

**Comment by SRombauts** [comment]
The root of the problem is that I am using this Items of the Changeset to detect the type of operation on the file (that is, Added, Changed, Renamed, Copied, etc.)
There might be a more straightforward way in Plastic SCM to get all the changes & details specific for the whole history of a file, that would not bring any info from other files

**Comment by Dzarg** [comment]
I see, I couldn't figure out a workaround either.

Are you in contact with or working for Codice? Could they help with this? I can also contact them for this feature request if you'd prefer that.

I think changing the format away from XML would already help over one magnitude, but I guess it might be a lot of work(?). I haven't checked that part of the code.

**Comment by SRombauts** [comment]
Yes I am in working for them on the plugin, I have asked for help with this.

And yes, I agree that moving away from XML, would be a workaround, but I hope we have a better way

**Comment by SRombauts** [comment]
So their long answer is:

1) I could use the `cm hist` command:

- cset // --format={changesetid}
- revision id (pretty hacker to show by the way) // --format={id}
- date // --format={date}
- comment // --format={comment}

But I don't have much time to dive into this right now, I could first update the current log commands to simply not retrieve items and have it already a lot quicker, just without rename detection.

2) Then, the "Action" field would need to use the following queries to detect renaming etc.:

- find removed where itemid =
- find moved where itemid =

The itemid field is a common ID for all the file revisions, you can get it locally using a `cm ls --format={itemid}` command.

**Comment by Dzarg** [comment]
Thanks for the info!

"I could first update the current log commands to simply not retrieve items and have it already a lot quicker, just without rename detection."
At least for our use case this sounds good. We very rarely rename/move files.

**Comment by SRombauts** [comment]
![image](https://user-images.githubusercontent.com/868490/69920778-54dd7d00-148c-11ea-9f40-aeb0e043adc0.png)
![image](https://user-images.githubusercontent.com/868490/69920814-bbfb3180-148c-11ea-9c04-90488845b0ef.png)
![image](https://user-images.githubusercontent.com/868490/69921004-8b1bfc00-148e-11ea-9f40-030f4ea7684c.png)

**Comment by SRombauts** [comment]
Hello @Dzarg, would you have the possibility to check the performances of the plugin with my latest code changes?

Let me know if this quite brutal simplification is good enough for you.
I would love to see one of this cool profiling chart from superluminal :)

Cheers!
Sébastien

**Comment by SRombauts** [comment]
In my particular case, on a big project with a slow laptop, the whole operation goes bellow 0.01s (instead of 20-30s) :)

**Comment by Dzarg** [comment]
![image](https://user-images.githubusercontent.com/94673/69937220-ce07bf00-14e2-11ea-807c-5ccfcd4c789f.png)

**Comment by SRombauts** [comment]
Oh dang, how did I miss that? Sorry, I am on it now!

The issue is obvious, it's because I am not retrieving the internal Revision Id of each version of the file.

**Comment by Dzarg** [comment]
Thanks! Now it works! My co-workers and I thank you for this! :)

As requested here's a superluminal profile of the history operation:
![image](https://user-images.githubusercontent.com/94673/70081034-68195580-1610-11ea-9463-db4ca8ab2511.png)
There's not much detail in this one about the operation. Most of the time was spent in slate and sleeping, so this is very good.

And then when doing a diff from something in the history:
![image](https://user-images.githubusercontent.com/94673/70084261-a6197800-1616-11ea-95e0-b96bbd88b82f.png)
Here it's mostly reading (peeking actually) the pipe. The total time is a bit high in this one. It seems to vary between ~instant to about 4 seconds (I haven't explored further). I tried having higher sleep time instead of 0, but it didn't seem to help (the total time varied wildly, so it was a bit hard to get reliable data). But this is good enough for us as it is now :)

**Comment by SRombauts** [comment]
Thanks to you for your report, with clear repro case and analysis, it was very helpful!

Thank you also for your profiling: superluminal looks awesome! I think I will try the new Insight tool of Unreal first, but it's a tool I should give a try at some point.
