### ISSUE TITLE
Issues with checking out tons of files IF Editor is running DX12

### ISSUE THREAD

**Issue by SRombauts** [SRombauts/UE4PlasticPlugin#93]
Reported today: We have issues with checking out tons of files IF editor is running dx12 - something leaks memory and UE crashes. Running in DX11 fixes that.

**Comment by kwljunky** [comment]
@SRombauts For me, the memory spikes up to 64gb usage and then states and out of memory video crash, running DX-11 did not quite help with this.

**Comment by SRombauts** [comment]
> For me, the memory spikes up to 64gb usage and then states and out of memory video crash, running DX-11 did not quite help with this.

@kwljunky thanks for the report, I am looking for more info on this; did you already report this to support?
(I do have least on log file from support)

My current take on this is that it seems to happen during very long source control operation ; eg checking in one big file

**Comment by kwljunky** [comment]
@SRombauts Yeah I did report this to Plastic SCM support, but they could not do anything because they wanted to access the project which we couldn't do. Can do a screenshare to show the issue with VS in the background if you did want to breakpoint it if that will help get to the issue faster. 

It does happen in long source control operations, but even moving files around will trigger it. I do think it is also related to repo size as well, as some of our users with 16gb of ram were reporting the issue and it was fine for me, but as the repo size has increased now the memory leak spikes over 64gb which causes even my rig to crash. 

This was tested on both 4.26 and 4.27 we are using 14.8 version of the plugin. 

The issue was also happening with blueprint diffing, but 14.8 did fix that so I was going to look into it after our studio deadline at the end of April to see what you did between 14.6-14.8 and potentially apply that with the other operations that are affected.

**Comment by SRombauts** [comment]
> The issue was also happening with blueprint diffing, but 14.8 did fix that
It was an issue with parsing the XML log of the repository instead of the history of the file, so it won't apply to other operations.

Also, the report I got was about a crash "out of Video memory"
hence the "fix with dx11"
so I suspect the issue you have or had is different then the one on this ticket

If you can provide some logs it would definitely help
the logs could include the callstack in plain text if you use the release "with debug symbols" or compile it yourself

**Comment by SRombauts** [comment]
This should now be worked around on master with https://github.com/SRombauts/UE4PlasticPlugin/commit/974ff8fbbefd7c95ef157f2ef04f70007888724e

**Comment by SRombauts** [comment]
For future me searching the info, it's tracked by the oldest issue #86 

----

[SRombauts](https://github.com/SRombauts) commented [21 days ago](https://github.com/SRombauts/UEPlasticPlugin/issues/86#issuecomment-1218373488) • 
I opened a PR for Epic Games to integrate the proper fix into Unreal Engine 5.1 hopefully:
https://github.com/EpicGames/UnrealEngine/pull/9492 [UE-100291][UE-160299] Fix source control progress bar crashing out of video memory in case of long-running operation #9492

----

[SRombauts](https://github.com/SRombauts) commented [13 days ago](https://github.com/SRombauts/UEPlasticPlugin/issues/86#issuecomment-1227601539)
The proper fix has been submitted to ue5-main https://github.com/EpicGames/UnrealEngine/commit/67dacf2baaafe0d9b6fb5eeb5b179fb5b871a4bf

It will be part of UE 5.1 release :)
